---
classes:
  - fuel_project::apps::firewall
  - fuel_project::common
  - fuel_project::nginx
  - log_storage::logstash
  - log_storage::logstashforwarder
  - log_storage::params
  - logstash
  - logstashforwarder
  - java

logstash::manage_repo: false
logstash::package_pin: true
logstash::version: '1.5.2-ubuntu2'

log_storage::logstash::elasticsearch_host:
  - 'storage01.test.local'
  - 'storage02.test.local'
log_storage::logstash::elasticsearch_port: '9201'
log_storage::logstash::elasticsearch_protocol: 'http'
log_storage::logstash::elasticsearch_ssl: true
log_storage::logstash::elasticsearch_ssl_cert_verify: 'false'
log_storage::logstash::lumberjack_host: '0.0.0.0'

logstashforwarder::servers:
  - '%{::fqdn}:5000'
  - 'storage-proxy.test.local:5000'

# firewall configuration
fuel_project::apps::firewall::rules:
   '1000 - allow connections from 1.1.1.0/23 - SRT location':
    source: 1.1.1.0/23
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.2.0/22 - MSK location':
    source: 1.1.2.0/22
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.6.0/24 - new US DC':
    source: 1.1.6.0/24
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.7.0/23 - KHA location':
    source: 1.1.7.0/23
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.8.0/29 - LVV location':
    source: 1.1.8.0/29
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.9.0/29 - MNV_1 location':
    source: 1.1.9.0/29
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.10.0/30 - MNV_2 location':
    source: 1.1.10.0/30
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.11.0/29 - MNV_3 location':
    source: 1.1.11.0/29
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.12.0/28 - POZ location':
    source: 1.1.12.0/28
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.13.0/32 - SanJose DC'
    source: 1.1.13.0/28
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept
  '1000 - allow connections from 1.1.14.0/24 - BUD DC'
    source: 1.1.14.0/24
    dport:
      - 22
      - 5000
    proto: tcp
    action: accept